/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa_Mobil;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author ACER
 */
public class daftar_akun extends javax.swing.JFrame {

    /**
     * Creates new form daftar_akun
     */
    public daftar_akun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new Sewa_Mobil.ButtonImage();
        daftar_akun = new Sewa_Mobil.ButtonImage();
        jenis_kelamin = new javax.swing.JComboBox<>();
        id_pelanggan = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telepon = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        nama_pelanggan = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 110));

        daftar_akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_akunActionPerformed(evt);
            }
        });
        getContentPane().add(daftar_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 770, 320, 90));

        jenis_kelamin.setBackground(new java.awt.Color(246, 246, 233));
        jenis_kelamin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jenis_kelamin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 350, 60));

        id_pelanggan.setBackground(new java.awt.Color(246, 246, 233));
        id_pelanggan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_pelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 350, 60));

        alamat.setBackground(new java.awt.Color(246, 246, 233));
        alamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 360, 60));

        telepon.setBackground(new java.awt.Color(246, 246, 233));
        telepon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        telepon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 350, 60));

        password1.setBackground(new java.awt.Color(246, 246, 233));
        password1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 360, 50));

        nama_pelanggan.setBackground(new java.awt.Color(246, 246, 233));
        nama_pelanggan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nama_pelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 296, 350, 70));

        umur.setBackground(new java.awt.Color(246, 246, 233));
        umur.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        umur.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 350, 60));

        password2.setBackground(new java.awt.Color(246, 246, 233));
        password2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, 370, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/daftar_customer.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        halaman_utama ha = new halaman_utama();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void daftar_akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_akunActionPerformed
        // TODO add your handling code here:
        String id=id_pelanggan.getText();
        String nama=nama_pelanggan.getText();
        String alamat1=alamat.getText();
        int umur1=Integer.parseInt(umur.getText());
        int tel=Integer.parseInt(telepon.getText());
        String jk=(String) jenis_kelamin.getSelectedItem();
        String password3=password1.getText();
        String password4=password2.getText();
        
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            PreparedStatement pat=kon.prepareStatement("insert into pelanggan values"+"('"+id+"','"+nama+"','"+alamat1+"','"+umur1+"','"+tel+"','"+jk+"','"+password3+"')");
            
            if(password3.equals(password4)){
                pat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Anda Berhasil Mendaftar");
                
                login_pelanggan ha = new login_pelanggan();
                ha.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Check Password Kamu Tidak Sinkron");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Isi Seluruh Data");
        }
    }//GEN-LAST:event_daftar_akunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private Sewa_Mobil.ButtonImage back;
    private Sewa_Mobil.ButtonImage daftar_akun;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
