/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa_Mobil;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class data_mobilDanpaketsewa extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form data_mobilDanpaketsewa
     */
    public data_mobilDanpaketsewa() {
        initComponents();
        String [] judul={"Plat Mobil","Merk Mobil","Jenis Mobil","Warna Mobil","Harga Sewa"};
        model = new DefaultTableModel(judul,0);
        info_mobilDansewa.setModel(model);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new Sewa_Mobil.ButtonImage();
        hapus = new Sewa_Mobil.ButtonImage();
        tambah = new Sewa_Mobil.ButtonImage();
        update = new Sewa_Mobil.ButtonImage();
        plat = new javax.swing.JTextField();
        merk = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        warna = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        info_mobilDansewa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 36, 110, 110));

        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 760, 270, 100));

        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 766, 280, 90));

        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 760, 270, 100));

        plat.setBackground(new java.awt.Color(246, 246, 233));
        plat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 210, 40));

        merk.setBackground(new java.awt.Color(246, 246, 233));
        merk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        merk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 530, 210, 40));

        jenis.setBackground(new java.awt.Color(246, 246, 233));
        jenis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 210, 40));

        harga.setBackground(new java.awt.Color(246, 246, 233));
        harga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        harga.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 696, 210, 40));

        warna.setBackground(new java.awt.Color(246, 246, 233));
        warna.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        warna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 696, 210, 40));

        info_mobilDansewa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        info_mobilDansewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        info_mobilDansewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_mobilDansewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(info_mobilDansewa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 1060, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/hal_admin (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        hal_admin ha = new hal_admin();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void info_mobilDansewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_mobilDansewaMouseClicked
        // TODO add your handling code here:
        int i = info_mobilDansewa.getSelectedRow();
        if(i>-1){
            plat.setText(model.getValueAt(i, 0).toString());
            merk.setText(model.getValueAt(i, 1).toString());
            jenis.setText(model.getValueAt(i, 2).toString());
            harga.setText(model.getValueAt(i, 4).toString());
            warna.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_info_mobilDansewaMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String plat1=plat.getText();
        String merk1=merk.getText();
        String jenis1=jenis.getText();
        String warna1=warna.getText();
        int harga1=Integer.parseInt(harga.getText());
        
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            kon.createStatement().executeUpdate("insert into mobil values"+"('"+plat1+"','"+merk1+"','"+jenis1+"','"+warna1+"','"+harga1+"')");
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Ditambahkan");
            
            data_mobilDanpaketsewa ha = new data_mobilDanpaketsewa();
            ha.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(data_mobilDanpaketsewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            kon.createStatement().executeUpdate("delete from mobil where data_mobil='"+plat.getText()+"'");
            JOptionPane.showMessageDialog(rootPane, "Data Sudah Dihapus");
            
            data_mobilDanpaketsewa ha = new data_mobilDanpaketsewa();
            ha.setVisible(true);
            this.dispose();
            
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       String plat1=plat.getText();
        String merk1=merk.getText();
        String jenis1=jenis.getText();
        String warna1=warna.getText();
        int harga1=Integer.parseInt(harga.getText());
        
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            kon.createStatement().executeUpdate("update mobil set merk='"+merk1+"',jenis='"+jenis1+"',warna='"+warna1+"',harga='"+harga1+"' where data_mobil='"+plat1+"'");
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Update");
            
            data_mobilDanpaketsewa ha = new data_mobilDanpaketsewa();
            ha.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_mobilDanpaketsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_mobilDanpaketsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_mobilDanpaketsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_mobilDanpaketsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_mobilDanpaketsewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sewa_Mobil.ButtonImage back;
    private Sewa_Mobil.ButtonImage hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JTable info_mobilDansewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField merk;
    private javax.swing.JTextField plat;
    private Sewa_Mobil.ButtonImage tambah;
    private Sewa_Mobil.ButtonImage update;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = info_mobilDansewa.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try {
            //To change body of generated methods, choose Tools | Templates.
            Connection as = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            ResultSet rs= as.createStatement().executeQuery("SELECT * FROM mobil");
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menyambungkan Database");
        }
    }
}
