/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa_Mobil;

/**
 *
 * @author ACER
 */
public class hal_login extends javax.swing.JFrame {

    /**
     * Creates new form hal_login
     */
    public hal_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new Sewa_Mobil.ButtonImage();
        login_pelanggan = new Sewa_Mobil.ButtonImage();
        login_pemimpin = new Sewa_Mobil.ButtonImage();
        buttonImage1 = new Sewa_Mobil.ButtonImage();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 30, 110, 120));

        login_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(login_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 570, 110));

        login_pemimpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_pemimpinActionPerformed(evt);
            }
        });
        getContentPane().add(login_pemimpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 500, 100));

        buttonImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImage1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 420, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/hal_login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         halaman_utama ha = new halaman_utama();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void login_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_pelangganActionPerformed
        // TODO add your handling code here:
        login_pelanggan ha = new login_pelanggan();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_pelangganActionPerformed

    private void login_pemimpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_pemimpinActionPerformed
        // TODO add your handling code here:
        login_pemimpin ha = new login_pemimpin();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_pemimpinActionPerformed

    private void buttonImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImage1ActionPerformed
        // TODO add your handling code here:
        login_admin ha = new login_admin();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonImage1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hal_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sewa_Mobil.ButtonImage back;
    private Sewa_Mobil.ButtonImage buttonImage1;
    private javax.swing.JLabel jLabel1;
    private Sewa_Mobil.ButtonImage login_pelanggan;
    private Sewa_Mobil.ButtonImage login_pemimpin;
    // End of variables declaration//GEN-END:variables
}
