/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa_Mobil;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class hal_pengembalian extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form hal_pengembalian
     */
    public hal_pengembalian() {
        initComponents();
        String [] judul={"ID SEWA","ID PELANGGAN","PLAT MOBIL","BIAYA","PELUNASAN"};
        model = new DefaultTableModel(judul,0);
        table_peminjaman.setModel(model);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_peminjaman = new javax.swing.JTable();
        back = new Sewa_Mobil.ButtonImage();
        id_sewa = new javax.swing.JTextField();
        data_mobil = new javax.swing.JTextField();
        biaya_sewa = new javax.swing.JTextField();
        pelunasan = new javax.swing.JTextField();
        kembalikan = new Sewa_Mobil.ButtonImage();
        id_pelanggan1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_peminjaman.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        table_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        table_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_peminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 580, 360));

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 120));

        id_sewa.setBackground(new java.awt.Color(246, 246, 233));
        id_sewa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_sewa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(id_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 360, 60));

        data_mobil.setBackground(new java.awt.Color(246, 246, 233));
        data_mobil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        data_mobil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(data_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 350, 70));

        biaya_sewa.setBackground(new java.awt.Color(246, 246, 233));
        biaya_sewa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        biaya_sewa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(biaya_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 350, 60));

        pelunasan.setBackground(new java.awt.Color(246, 246, 233));
        pelunasan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pelunasan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(pelunasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 350, 60));

        kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikanActionPerformed(evt);
            }
        });
        getContentPane().add(kembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 790, 270, 100));

        id_pelanggan1.setBackground(new java.awt.Color(246, 246, 233));
        id_pelanggan1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_pelanggan1.setText("\n");
        id_pelanggan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(id_pelanggan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 350, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/hal_customer (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        hal_pinjam ha = new hal_pinjam();
        ha.setVisible(true);                    //berpindah Halaman
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void kembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanActionPerformed
        try {
            // TODO add your handling code here:
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            kon.createStatement().executeUpdate("delete from penyewaan where sewa_id='"+id_sewa.getText()+"'");
            JOptionPane.showMessageDialog(rootPane, "Mobil Telah Dikembalikan");
            
            info_peminjaman ha = new info_peminjaman();
            ha.setVisible(true);
            this.dispose();
            
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_kembalikanActionPerformed

    private void table_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_peminjamanMouseClicked
        // TODO add your handling code here:
        int i = table_peminjaman.getSelectedRow();
        if(i>-1){
            id_sewa.setText(model.getValueAt(i, 0).toString());
            id_pelanggan1.setText(model.getValueAt(i, 1).toString());
            data_mobil.setText(model.getValueAt(i, 2).toString());
            biaya_sewa.setText(model.getValueAt(i, 3).toString());
            pelunasan.setText(model.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_table_peminjamanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hal_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hal_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hal_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hal_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hal_pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sewa_Mobil.ButtonImage back;
    private javax.swing.JTextField biaya_sewa;
    private javax.swing.JTextField data_mobil;
    private javax.swing.JTextField id_pelanggan1;
    private javax.swing.JTextField id_sewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Sewa_Mobil.ButtonImage kembalikan;
    private javax.swing.JTextField pelunasan;
    private javax.swing.JTable table_peminjaman;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
         int row = table_peminjaman.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try {
            //To change body of generated methods, choose Tools | Templates.
            Connection as = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            ResultSet rs= as.createStatement().executeQuery("SELECT * FROM penyewaan");
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menyambungkan Database");
        }
    }
}
