/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa_Mobil;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;

public class login_admin extends javax.swing.JFrame {

    /**
     * Creates new form login_admin
     */
    public login_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_admin = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        back = new Sewa_Mobil.ButtonImage();
        login2 = new Sewa_Mobil.ButtonImage();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_admin.setBackground(new java.awt.Color(246, 246, 233));
        id_admin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(id_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 340, 60));

        password.setBackground(new java.awt.Color(246, 246, 233));
        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 340, 70));

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 280, 100));

        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });
        getContentPane().add(login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 270, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/login_admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        hal_login ha = new hal_login();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:
        String id=id_admin.getText();
        String password1=password.getText();

        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/sewamobil","root","");
            ResultSet as = kon.createStatement().executeQuery("select * from admin where id_admin='"+id+"' and password='"+password1+"'");
            while(as.next()){
                id=as.getString("id_admin");
            }
            as.last();
            if(as.getRow()==1){
                register.setid(id);
                JOptionPane.showMessageDialog(rootPane, "Anda Berhasil Login");
                hal_admin ha = new hal_admin();
                ha.setVisible(true);
                this.dispose();
            } else{
                JOptionPane.showMessageDialog(rootPane, "Password Atau ID salah");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(login_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sewa_Mobil.ButtonImage back;
    private javax.swing.JTextField id_admin;
    private javax.swing.JLabel jLabel1;
    private Sewa_Mobil.ButtonImage login2;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
